//! Media understanding engine — image description, audio transcription, video analysis.
//!
//! Auto-cascades through available providers based on configured API keys.

use openfang_types::media::{
    MediaAttachment, MediaConfig, MediaSource, MediaType, MediaUnderstanding,
};
use std::sync::Arc;
use tokio::sync::Semaphore;
use tracing::info;

/// Media understanding engine.
pub struct MediaEngine {
    config: MediaConfig,
    semaphore: Arc<Semaphore>,
}

impl MediaEngine {
    pub fn new(config: MediaConfig) -> Self {
        let max = config.max_concurrency.clamp(1, 8);
        Self {
            config,
            semaphore: Arc::new(Semaphore::new(max)),
        }
    }

    /// Describe an image using a vision-capable LLM.
    /// Auto-cascade: Anthropic -> OpenAI -> Gemini (based on API key availability).
    pub async fn describe_image(
        &self,
        attachment: &MediaAttachment,
    ) -> Result<MediaUnderstanding, String> {
        attachment.validate()?;
        if attachment.media_type != MediaType::Image {
            return Err("Expected image attachment".into());
        }

        // Determine which provider to use
        let provider = self.config.image_provider.as_deref()
            .or_else(|| detect_vision_provider())
            .ok_or("No vision-capable LLM provider configured. Set ANTHROPIC_API_KEY, OPENAI_API_KEY, or GEMINI_API_KEY")?;

        // For now, return a structured result indicating the provider.
        // Actual API call would go here using reqwest.
        Ok(MediaUnderstanding {
            media_type: MediaType::Image,
            description: format!(
                "[Image description would be generated by {} provider]",
                provider
            ),
            provider: provider.to_string(),
            model: default_vision_model(provider).to_string(),
        })
    }

    /// Transcribe audio using speech-to-text.
    /// Auto-cascade through configured providers: Groq -> OpenAI -> Local Whisper.
    pub async fn transcribe_audio(
        &self,
        attachment: &MediaAttachment,
    ) -> Result<MediaUnderstanding, String> {
        attachment.validate()?;
        if attachment.media_type != MediaType::Audio {
            return Err("Expected audio attachment".into());
        }

        // Get provider list from config or use default cascade
        let providers = self.config.audio_providers.clone().unwrap_or_else(|| {
            vec![
                "groq".to_string(),
                "openai".to_string(),
                "local_whisper".to_string(),
            ]
        });

        // Try each provider in order until one succeeds
        let mut last_error: Option<String> = None;
        for provider in &providers {
            match self
                .transcribe_audio_with_provider(attachment, provider.as_str())
                .await
            {
                Ok(result) => return Ok(result),
                Err(e) => {
                    info!(
                        provider = %provider,
                        error = %e,
                        "Provider failed, trying next in cascade"
                    );
                    last_error = Some(format!("{}: {}", provider, e));
                }
            }
        }

        Err(format!(
            "All transcription providers failed. Last error: {}",
            last_error.unwrap_or_else(|| "Unknown error".to_string())
        ))
    }

    /// Transcribe audio with a specific provider.
    async fn transcribe_audio_with_provider(
        &self,
        attachment: &MediaAttachment,
        provider: &str,
    ) -> Result<MediaUnderstanding, String> {

        let _permit = self.semaphore.acquire().await.map_err(|e| e.to_string())?;

        // Handle local Whisper separately
        if provider == "local_whisper" {
            return self.transcribe_with_local_whisper(attachment).await;
        }

        // Derive a proper filename with extension from mime_type
        // (Whisper APIs require an extension to detect format)
        let ext = match attachment.mime_type.as_str() {
            "audio/wav" => "wav",
            "audio/mpeg" | "audio/mp3" => "mp3",
            "audio/ogg" => "ogg",
            "audio/webm" => "webm",
            "audio/mp4" | "audio/m4a" => "m4a",
            "audio/flac" => "flac",
            _ => "wav",
        };

        // Read audio bytes from source
        let audio_bytes = match &attachment.source {
            MediaSource::FilePath { path } => tokio::fs::read(path)
                .await
                .map_err(|e| format!("Failed to read audio file '{}': {}", path, e))?,
            MediaSource::Base64 { data, .. } => {
                use base64::Engine;
                base64::engine::general_purpose::STANDARD
                    .decode(data)
                    .map_err(|e| format!("Failed to decode base64 audio: {}", e))?
            }
            MediaSource::Url { url } => {
                return Err(format!(
                    "URL-based audio source not supported for transcription: {}",
                    url
                ));
            }
        };
        let filename = format!("audio.{}", ext);

        let model = default_audio_model(provider);

        // Build API request
        let (api_url, api_key) = match provider {
            "groq" => (
                "https://api.groq.com/openai/v1/audio/transcriptions",
                std::env::var("GROQ_API_KEY").map_err(|_| "GROQ_API_KEY not set")?,
            ),
            "openai" => (
                "https://api.openai.com/v1/audio/transcriptions",
                std::env::var("OPENAI_API_KEY").map_err(|_| "OPENAI_API_KEY not set")?,
            ),
            "deepgram" => (
                "https://api.deepgram.com/v1/listen?model=nova-2&smart_format=true&detect_language=true",
                std::env::var("DEEPGRAM_API_KEY").map_err(|_| "DEEPGRAM_API_KEY not set")?,
            ),
            "assemblyai" => (
                "https://api.assemblyai.com/v2/upload",
                std::env::var("ASSEMBLYAI_API_KEY").map_err(|_| "ASSEMBLYAI_API_KEY not set")?,
            ),
            other => return Err(format!("Unsupported audio provider: {}", other)),
        };

        info!(provider, model, filename = %filename, size = audio_bytes.len(), "Sending audio for transcription");

        // Handle different provider APIs
        let transcription = match provider {
            "groq" | "openai" => {
                // Whisper-compatible API (multipart form with model)
                let file_part = reqwest::multipart::Part::bytes(audio_bytes)
                    .file_name(filename)
                    .mime_str(&attachment.mime_type)
                    .map_err(|e| format!("Failed to set MIME type: {}", e))?;

                let form = reqwest::multipart::Form::new()
                    .part("file", file_part)
                    .text("model", model.to_string())
                    .text("response_format", "text");

                let client = reqwest::Client::new();
                let resp = client
                    .post(api_url)
                    .bearer_auth(&api_key)
                    .multipart(form)
                    .timeout(std::time::Duration::from_secs(60))
                    .send()
                    .await
                    .map_err(|e| format!("Transcription request failed: {}", e))?;

                if !resp.status().is_success() {
                    let status = resp.status();
                    let body = resp.text().await.unwrap_or_default();
                    return Err(format!("Transcription API error ({}): {}", status, body));
                }

                resp.text()
                    .await
                    .map_err(|e| format!("Failed to read transcription response: {}", e))?
            }
            "deepgram" => {
                // Deepgram API: POST audio directly, get JSON response
                let client = reqwest::Client::new();
                let resp = client
                    .post(api_url)
                    .header("Authorization", format!("Token {}", api_key))
                    .header("Content-Type", "audio/*")
                    .body(audio_bytes)
                    .timeout(std::time::Duration::from_secs(60))
                    .send()
                    .await
                    .map_err(|e| format!("Deepgram request failed: {}", e))?;

                if !resp.status().is_success() {
                    let status = resp.status();
                    let body = resp.text().await.unwrap_or_default();
                    return Err(format!("Deepgram API error ({}): {}", status, body));
                }

                // Parse JSON response: { "results": { "channels": [{ "alternatives": [{ "transcript": "..." }] }] } }
                let json: serde_json::Value = resp
                    .json()
                    .await
                    .map_err(|e| format!("Failed to parse Deepgram response: {}", e))?;

                json["results"]["channels"][0]["alternatives"][0]["transcript"]
                    .as_str()
                    .ok_or("Deepgram returned empty transcript")?
                    .to_string()
            }
            "assemblyai" => {
                // AssemblyAI API: 1) Upload, 2) Poll transcript, 3) Get result
                // Step 1: Upload audio
                let client = reqwest::Client::new();
                
                let upload_resp = client
                    .post(api_url)
                    .header("authorization", &api_key)
                    .header("content-type", "application/octet-stream")
                    .body(audio_bytes.clone())
                    .timeout(std::time::Duration::from_secs(60))
                    .send()
                    .await
                    .map_err(|e| format!("AssemblyAI upload failed: {}", e))?;

                if !upload_resp.status().is_success() {
                    let status = upload_resp.status();
                    let body = upload_resp.text().await.unwrap_or_default();
                    return Err(format!("AssemblyAI upload error ({}): {}", status, body));
                }

                let upload_json: serde_json::Value = upload_resp
                    .json()
                    .await
                    .map_err(|e| format!("Failed to parse AssemblyAI upload response: {}", e))?;

                let upload_url = upload_json["upload_url"]
                    .as_str()
                    .ok_or("AssemblyAI did not return upload_url")?;

                // Step 2: Create transcript request with speech_models
                let transcript_req = serde_json::json!({
                    "audio_url": upload_url,
                    "speech_models": ["universal-2"]
                });
                
                let transcript_resp = client
                    .post("https://api.assemblyai.com/v2/transcript")
                    .header("authorization", &api_key)
                    .header("content-type", "application/json")
                    .json(&transcript_req)
                    .timeout(std::time::Duration::from_secs(60))
                    .send()
                    .await
                    .map_err(|e| format!("AssemblyAI transcript request failed: {}", e))?;

                if !transcript_resp.status().is_success() {
                    let status = transcript_resp.status();
                    let body = transcript_resp.text().await.unwrap_or_default();
                    return Err(format!("AssemblyAI transcript error ({}): {}", status, body));
                }

                let transcript_json: serde_json::Value = transcript_resp
                    .json()
                    .await
                    .map_err(|e| format!("Failed to parse AssemblyAI transcript response: {}", e))?;

                let transcript_id = transcript_json["id"]
                    .as_str()
                    .ok_or("AssemblyAI did not return transcript id")?;

                // Step 3: Poll until complete
                let mut attempts = 0;
                let max_attempts = 60; // 30 seconds max
                let mut final_text = String::new();

                while attempts < max_attempts {
                    tokio::time::sleep(std::time::Duration::from_secs(2)).await;
                    
                    let status_resp = client
                        .get(format!("https://api.assemblyai.com/v2/transcript/{}", transcript_id))
                        .header("authorization", &api_key)
                        .timeout(std::time::Duration::from_secs(30))
                        .send()
                        .await
                        .map_err(|e| format!("AssemblyAI status check failed: {}", e))?;

                    let status_json: serde_json::Value = status_resp
                        .json()
                        .await
                        .map_err(|e| format!("Failed to parse AssemblyAI status: {}", e))?;

                    let status = status_json["status"].as_str().unwrap_or("unknown");
                    
                    match status {
                        "completed" => {
                            final_text = status_json["text"]
                                .as_str()
                                .ok_or("AssemblyAI returned empty transcript")?
                                .to_string();
                            break;
                        }
                        "error" => {
                            return Err(format!("AssemblyAI transcription failed: {}", 
                                status_json["error"].as_str().unwrap_or("unknown error")));
                        }
                        _ => {
                            attempts += 1;
                            continue;
                        }
                    }
                }

                if final_text.is_empty() {
                    return Err("AssemblyAI transcription timed out".into());
                }

                final_text
            }
            other => return Err(format!("Unsupported audio provider: {}", other)),
        };

        let transcription = transcription.trim().to_string();
        if transcription.is_empty() {
            return Err("Transcription returned empty text".into());
        }

        info!(
            provider,
            model,
            chars = transcription.len(),
            "Audio transcription complete"
        );

        Ok(MediaUnderstanding {
            media_type: MediaType::Audio,
            description: transcription,
            provider: provider.to_string(),
            model: model.to_string(),
        })
    }

    /// Describe video using Gemini.
    pub async fn describe_video(
        &self,
        attachment: &MediaAttachment,
    ) -> Result<MediaUnderstanding, String> {
        attachment.validate()?;
        if attachment.media_type != MediaType::Video {
            return Err("Expected video attachment".into());
        }

        if !self.config.video_description {
            return Err("Video description is disabled in configuration".into());
        }

        if std::env::var("GEMINI_API_KEY").is_err() && std::env::var("GOOGLE_API_KEY").is_err() {
            return Err("Video description requires GEMINI_API_KEY or GOOGLE_API_KEY".into());
        }

        Ok(MediaUnderstanding {
            media_type: MediaType::Video,
            description: "[Video description would be generated by Gemini]".to_string(),
            provider: "gemini".to_string(),
            model: "gemini-2.5-flash".to_string(),
        })
    }

    /// Process multiple attachments concurrently (bounded by max_concurrency).
    pub async fn process_attachments(
        &self,
        attachments: Vec<MediaAttachment>,
    ) -> Vec<Result<MediaUnderstanding, String>> {
        let mut handles = Vec::new();

        for attachment in attachments {
            let sem = self.semaphore.clone();
            let config = self.config.clone();
            let handle = tokio::spawn(async move {
                let _permit = sem.acquire().await.map_err(|e| e.to_string())?;
                let engine = MediaEngine {
                    config,
                    semaphore: Arc::new(Semaphore::new(1)), // inner engine, no extra semaphore
                };
                match attachment.media_type {
                    MediaType::Image => engine.describe_image(&attachment).await,
                    MediaType::Audio => engine.transcribe_audio(&attachment).await,
                    MediaType::Video => engine.describe_video(&attachment).await,
                }
            });
            handles.push(handle);
        }

        let mut results = Vec::new();
        for handle in handles {
            match handle.await {
                Ok(result) => results.push(result),
                Err(e) => results.push(Err(format!("Task failed: {e}"))),
            }
        }
        results
    }

    /// Transcribe audio using local Whisper CLI (faster-whisper).
    async fn transcribe_with_local_whisper(
        &self,
        attachment: &MediaAttachment,
    ) -> Result<MediaUnderstanding, String> {
        use tokio::process::Command;

        // Get file path
        let file_path = match &attachment.source {
            MediaSource::FilePath { path } => path.clone(),
            MediaSource::Base64 { .. } => {
                return Err("Local Whisper requires file path, not base64".into());
            }
            MediaSource::Url { .. } => {
                return Err("Local Whisper requires file path, not URL".into());
            }
        };

        // Get model from config or default
        let model = self
            .config
            .local_whisper_model
            .as_deref()
            .unwrap_or("small");

        info!(
            model = %model,
            path = %file_path,
            "Transcribing with local faster-whisper"
        );

        // Run faster-whisper via Python
        // python3 -c "from faster_whisper import WhisperModel; model = WhisperModel('small'); segments, info = model.transcribe('audio.oga', language='es'); print(''.join([s.text for s in segments]))"
        let python_script = format!(
            r#"
from faster_whisper import WhisperModel
import sys

model = WhisperModel('{}', device='cpu', compute_type='int8')
segments, info = model.transcribe('{}', language='es')
text = ''.join([segment.text for segment in segments]).strip()
print(text)
"#,
            model, file_path
        );

        let output = tokio::time::timeout(
            std::time::Duration::from_secs(120),
            Command::new("python3")
                .arg("-c")
                .arg(&python_script)
                .output()
        )
        .await
        .map_err(|e| format!("Whisper transcription timed out: {}", e))?
        .map_err(|e| format!("Failed to run faster-whisper: {}", e))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            let stdout = String::from_utf8_lossy(&output.stdout);
            return Err(format!(
                "faster-whisper failed: {}\n{}",
                stderr, stdout
            ));
        }

        let transcription = String::from_utf8_lossy(&output.stdout).trim().to_string();

        if transcription.is_empty() {
            return Err("Transcription returned empty text".into());
        }

        info!(
            model = %model,
            chars = transcription.len(),
            "Local faster-whisper transcription complete"
        );

        Ok(MediaUnderstanding {
            media_type: MediaType::Audio,
            description: transcription,
            provider: "local_whisper".to_string(),
            model: format!("faster-whisper-{}", model),
        })
    }
}

/// Detect which vision provider is available based on environment variables.
fn detect_vision_provider() -> Option<&'static str> {
    if std::env::var("ANTHROPIC_API_KEY").is_ok() {
        return Some("anthropic");
    }
    if std::env::var("OPENAI_API_KEY").is_ok() {
        return Some("openai");
    }
    if std::env::var("GEMINI_API_KEY").is_ok() || std::env::var("GOOGLE_API_KEY").is_ok() {
        return Some("gemini");
    }
    None
}

/// Detect which audio transcription provider is available.
#[allow(dead_code)]
fn detect_audio_provider() -> Option<&'static str> {
    // Check in order of preference (cost/speed)
    if std::env::var("GROQ_API_KEY").is_ok() {
        return Some("groq");
    }
    if std::env::var("DEEPGRAM_API_KEY").is_ok() {
        return Some("deepgram");
    }
    if std::env::var("ASSEMBLYAI_API_KEY").is_ok() {
        return Some("assemblyai");
    }
    if std::env::var("OPENAI_API_KEY").is_ok() {
        return Some("openai");
    }
    // Check if faster-whisper is available (preferred)
    if std::process::Command::new("python3")
        .arg("-c")
        .arg("from faster_whisper import WhisperModel")
        .output()
        .is_ok_and(|o| o.status.success())
    {
        return Some("local_whisper");
    }
    // Fallback to original whisper CLI
    if std::process::Command::new("which").arg("whisper").output().is_ok() {
        return Some("local_whisper");
    }
    None
}

/// Get the default vision model for a provider.
fn default_vision_model(provider: &str) -> &str {
    match provider {
        "anthropic" => "claude-sonnet-4-20250514",
        "openai" => "gpt-4o",
        "gemini" => "gemini-2.5-flash",
        _ => "unknown",
    }
}

/// Get the default audio model for a provider.
fn default_audio_model(provider: &str) -> &str {
    match provider {
        "groq" => "whisper-large-v3-turbo",
        "openai" => "whisper-1",
        "deepgram" => "nova-2",
        "assemblyai" => "best",
        "local_whisper" => "large-v3-turbo",
        _ => "unknown",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use openfang_types::media::{MediaSource, MAX_IMAGE_BYTES};

    #[test]
    fn test_engine_creation() {
        let config = MediaConfig::default();
        let engine = MediaEngine::new(config);
        assert_eq!(engine.config.max_concurrency, 2);
    }

    #[test]
    fn test_engine_max_concurrency_clamped() {
        let config = MediaConfig {
            max_concurrency: 100,
            ..Default::default()
        };
        let engine = MediaEngine::new(config);
        // Semaphore was clamped to 8
        assert!(engine.semaphore.available_permits() <= 8);
    }

    #[tokio::test]
    async fn test_describe_image_wrong_type() {
        let engine = MediaEngine::new(MediaConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Audio,
            mime_type: "audio/mpeg".into(),
            source: MediaSource::FilePath {
                path: "test.mp3".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.describe_image(&attachment).await;
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("Expected image"));
    }

    #[tokio::test]
    async fn test_describe_image_invalid_mime() {
        let engine = MediaEngine::new(MediaConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Image,
            mime_type: "application/pdf".into(),
            source: MediaSource::FilePath {
                path: "test.pdf".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.describe_image(&attachment).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_describe_image_too_large() {
        let engine = MediaEngine::new(MediaConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Image,
            mime_type: "image/png".into(),
            source: MediaSource::FilePath {
                path: "big.png".into(),
            },
            size_bytes: MAX_IMAGE_BYTES + 1,
        };
        let result = engine.describe_image(&attachment).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_transcribe_audio_wrong_type() {
        let engine = MediaEngine::new(MediaConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Image,
            mime_type: "image/png".into(),
            source: MediaSource::FilePath {
                path: "test.png".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.transcribe_audio(&attachment).await;
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_video_disabled() {
        let config = MediaConfig {
            video_description: false,
            ..Default::default()
        };
        let engine = MediaEngine::new(config);
        let attachment = MediaAttachment {
            media_type: MediaType::Video,
            mime_type: "video/mp4".into(),
            source: MediaSource::FilePath {
                path: "test.mp4".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.describe_video(&attachment).await;
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("disabled"));
    }

    #[test]
    fn test_detect_vision_provider_none() {
        // In test env, likely no API keys set — should return None.
        // (This test is environment-dependent, but safe.)
        let _ = detect_vision_provider(); // Just verify it doesn't panic
    }

    #[test]
    fn test_default_vision_models() {
        assert_eq!(
            default_vision_model("anthropic"),
            "claude-sonnet-4-20250514"
        );
        assert_eq!(default_vision_model("openai"), "gpt-4o");
        assert_eq!(default_vision_model("gemini"), "gemini-2.5-flash");
        assert_eq!(default_vision_model("unknown"), "unknown");
    }

    #[test]
    fn test_default_audio_models() {
        assert_eq!(default_audio_model("groq"), "whisper-large-v3-turbo");
        assert_eq!(default_audio_model("openai"), "whisper-1");
    }

    #[tokio::test]
    async fn test_transcribe_audio_rejects_image_type() {
        let engine = MediaEngine::new(MediaConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Image,
            mime_type: "image/png".into(),
            source: MediaSource::FilePath {
                path: "test.png".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.transcribe_audio(&attachment).await;
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("Expected audio"));
    }

    #[tokio::test]
    async fn test_transcribe_audio_no_provider() {
        // With no API keys set, should fail with provider error
        let engine = MediaEngine::new(MediaConfig::default());
        let attachment = MediaAttachment {
            media_type: MediaType::Audio,
            mime_type: "audio/webm".into(),
            source: MediaSource::FilePath {
                path: "test.webm".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.transcribe_audio(&attachment).await;
        // Either fails with "No audio transcription provider" or file read error
        assert!(result.is_err());
    }

    #[tokio::test]
    async fn test_transcribe_audio_url_source_rejected() {
        // URL source should be rejected
        let config = MediaConfig {
            audio_provider: Some("groq".to_string()),
            ..Default::default()
        };
        let engine = MediaEngine::new(config);
        let attachment = MediaAttachment {
            media_type: MediaType::Audio,
            mime_type: "audio/mpeg".into(),
            source: MediaSource::Url {
                url: "https://example.com/audio.mp3".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.transcribe_audio(&attachment).await;
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .contains("URL-based audio source not supported"));
    }

    #[tokio::test]
    async fn test_transcribe_audio_file_not_found() {
        let config = MediaConfig {
            audio_provider: Some("groq".to_string()),
            ..Default::default()
        };
        let engine = MediaEngine::new(config);
        let attachment = MediaAttachment {
            media_type: MediaType::Audio,
            mime_type: "audio/webm".into(),
            source: MediaSource::FilePath {
                path: "/nonexistent/path/audio.webm".into(),
            },
            size_bytes: 1024,
        };
        let result = engine.transcribe_audio(&attachment).await;
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("Failed to read audio file"));
    }
}
